<?php

namespace MehdiBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function byCategorie($categorie)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.categorie = :categorie')
            ->orderBy(('u.id'))
            ->setParameter('categorie', $categorie);
        return $qb->getQuery()->getResult();
    }

    public function findProduitDQL($serie)
    {
        $query=$this->getEntityManager()
            ->createQuery("Select p from MehdiBundle:Produit p 
              where p.nomProduit =:serie")
            ->setParameter('serie',$serie);
        return $query->getResult();
    }

    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.id IN (:array)')
            ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }

}