actualite:
    resource: "@ActualiteBundle/Resources/config/routing.yml"
    prefix:   /actualite

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /event

mehdi:
    resource: "@MehdiBundle/Resources/config/routing.yml"
    prefix:   /mehdi

front2:
    resource: "@Front2Bundle/Resources/config/routing.yml"
    prefix:   /front


admin:
    resource: "@adminBundle/Resources/config/routing.yml"
    prefix:   /aa

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

