<?php

namespace SAVBundle\Repository;
use SAVBundle\Entity\Livraison;

/**
 * LivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivraisonRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Livraison[]
     */
    public function findAllNotFinished()
    {
        return $this->createQueryBuilder('l')
            ->andWhere('l.etat != :etat')
            ->setParameter('etat', 100)
            ->getQuery()
            ->execute();
    }
}
