<?php

namespace EvenementBundle\Repository;

/**
 * UserERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserERepository extends \Doctrine\ORM\EntityRepository
{
}
