gestion_boutiques_homepage:
    path:     /
    defaults: { _controller: GestionBoutiquesBundle:Default:index }

_afficher_boutiques:
    path:     /user/AfficherBoutiques
    defaults: { _controller: GestionBoutiquesBundle:Gestion:AfficherBoutiques }

_afficher_boutiques2:
    path:     /user/AfficherBoutiques2
    defaults: { _controller: GestionBoutiquesBundle:Gestion:AfficherBoutiques2 }

_supprimer_boutiques:
    path:     /SupprimerBoutiques
    defaults: { _controller: GestionBoutiquesBundle:Gestion:SupprimerBoutiques }

verifier_demandes:
    path:     /admin/verifierDemandes
    defaults: { _controller: GestionBoutiquesBundle:Admin:verifierDemandes }

affecter_boutique:
    path:     /admin/affecterBoutique
    defaults: { _controller: GestionBoutiquesBundle:Admin:affecterBoutique }

testbougalb:
    path:     /admin/test
    defaults: { _controller: GestionBoutiquesBundle:Gestion:ajoutimg }

espace_boutique:
    path:     /user/espaceBoutique
    defaults: { _controller: GestionBoutiquesBundle:Gestion:espaceBoutique }

envoi_dmde_vers_admin:
    path:     /user/envoyerdmdeboutique
    defaults: { _controller: GestionBoutiquesBundle:Gestion:envoiDemande }

ajout_produit_boutique:
    path:     /user/ajouterProd
    defaults: { _controller: GestionBoutiquesBundle:Gestion:ajoutProduit }

modifier_boutique:
    path:     /user/modifBoutique
    defaults: { _controller: GestionBoutiquesBundle:Gestion:modifierBoutique }

supprimer_prod:
    path:     /user/supp_prod
    defaults: { _controller: GestionBoutiquesBundle:Gestion:supprimerProduit }

modifier_produit:
    path:     /user/modifProduit
    defaults: { _controller: GestionBoutiquesBundle:Gestion:modifierProduit }

test_api:
    path:     /testapi
    defaults: { _controller: GestionBoutiquesBundle:Admin:testapi }

afficher_prods_boutiques:
    path:     /user/afficherProdBoutique
    defaults: { _controller: GestionBoutiquesBundle:Gestion:afficherProduitsBoutique }

ajouter_prod_au_panier:
    path:     /user/ajouterprodaupanier
    defaults: { _controller: GestionBoutiquesBundle:Panier:ajoutAuPanier }

afficher_panier:
    path:     /user/affichermonpanier
    defaults: { _controller: GestionBoutiquesBundle:Panier:afficherPanier }

supprimer_du_panier:
    path:     /user/supprimerdemonpanier
    defaults: { _controller: GestionBoutiquesBundle:Panier:suppDeMonPanier }

creer_commande:
    path:     /user/creerCommande
    defaults: { _controller: GestionBoutiquesBundle:Panier:creerCommande }

recherche_ajax:
    path:     /user/rechercheAjax
    defaults: { _controller: GestionBoutiquesBundle:Gestion:rechercheAjax }
