<?php

namespace GestionBoutiquesBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCategoriesBoutiqueDQL($boutiqueid)
    {
        $query=$this->getEntityManager()
            ->createQuery("Select cat.id from GestionBoutiquesBundle:ProduitBoutique prod JOIN prod.categorie cat
              WHERE prod.boutique=:boutiqueid ")
            //->setMaxResults(4)
            ->setParameter('boutiqueid',$boutiqueid);
        return $query->getResult();
    }
}
