<?php

namespace GestionBoutiquesBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findDernierProdsDQL($unid)
    {
        $query=$this->getEntityManager()
            ->createQuery("Select prod.id from GestionBoutiquesBundle:Commande comm JOIN comm.produit prod
              WHERE prod.boutique=:unid ")
            ->setMaxResults(4)
            ->setParameter('unid',$unid);
        return $query->getResult();
    }
}
