<?php

namespace GestionBoutiquesBundle\Repository;

/**
 * ProduitBoutiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitBoutiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
