<?php

namespace SAVBundle\Repository;

/**
 * demandeLivreurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demandeLivreurRepository extends \Doctrine\ORM\EntityRepository
{
}
