<?php

namespace SAVBundle\Repository;

/**
 * FullAdressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FullAdressRepository extends \Doctrine\ORM\EntityRepository
{
}
