gestion_boutiques:
    resource: "@GestionBoutiquesBundle/Resources/config/routing.yml"
    prefix:   /boutique

sav:
    resource: "@SAVBundle/Resources/config/routing.yml"
    prefix:   /sav

actualite:
    resource: "@ActualiteBundle/Resources/config/routing.yml"
    prefix:   /actualite

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /event

mehdi:
    resource: "@MehdiBundle/Resources/config/routing.yml"
    prefix:   /mehdi


admin:
    resource: "@adminBundle/Resources/config/routing.yml"
    prefix:   /aa

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

