a_index:
    path:     /
    defaults: { _controller: "ActualiteBundle:Actualite:index" }
    methods:  GET

a_show:
    path:     /{id}/show
    defaults: { _controller: "ActualiteBundle:Actualite:show" }
    methods:  GET

a_new:
    path:     /admin/new
    defaults: { _controller: "ActualiteBundle:Actualite:new" }
    methods:  [GET, POST]

a_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "ActualiteBundle:Actualite:edit" }
    methods:  [GET, POST]

a_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "ActualiteBundle:Actualite:delete" }
    methods:  [GET, POST]

a_manipulation:
    path:     /admin/manipulation
    defaults: { _controller: "ActualiteBundle:Actualite:manipulation" }
    methods:  GET

a_recherche:
    path:     /recherche
    defaults: { _controller: "ActualiteBundle:Actualite:recherche" }
    methods:  GET




