admin_homepage:
    path:     /
    defaults: { _controller: adminBundle:Default:index }

index:
    path:     /index
    defaults: { _controller: adminBundle:Admin:index }

layout:
    path:     /layout
    defaults: { _controller: adminBundle:Admin:layout }

index2:
    path:     /index2
    defaults: { _controller: adminBundle:Admin:index2 }

index3:
    path:     /index3
    defaults: { _controller: adminBundle:Admin:index3 }

calendar:
    path:     /calendar
    defaults: { _controller: adminBundle:Admin:calendar }

chat:
    path:     /chat
    defaults: { _controller: adminBundle:Admin:chat }

ticket:
    path:     /ticket
    defaults: { _controller: adminBundle:Admin:ticket }

contact1:
    path:     /contact1
    defaults: { _controller: adminBundle:Admin:contact1 }

contact2:
    path:     /contact2
    defaults: { _controller: adminBundle:Admin:contact2 }

mail:
    path:     /mail
    defaults: { _controller: adminBundle:Admin:mail }

maild:
    path:     /maild
    defaults: { _controller: adminBundle:Admin:maild }

compose:
    path:     /compose
    defaults: { _controller: adminBundle:Admin:compose }


cards:
    path:     /cards
    defaults: { _controller: adminBundle:Admin:cards }

usercards:
    path:     /usercards
    defaults: { _controller: adminBundle:Admin:usercards }

bouton:
    path:     /bouton
    defaults: { _controller: adminBundle:Admin:bouton }

modals:
    path:     /modals
    defaults: { _controller: adminBundle:Admin:modals }

tab:
    path:     /tab
    defaults: { _controller: adminBundle:Admin:tab }

tooltip:
    path:     /tooltip
    defaults: { _controller: adminBundle:Admin:tooltip }

tooltips:
    path:     /tooltips
    defaults: { _controller: adminBundle:Admin:tooltips }

suitalert:
    path:     /suitalert
    defaults: { _controller: adminBundle:Admin:suitalert }

notification:
    path:     /notification
    defaults: { _controller: adminBundle:Admin:notification }

progressbar:
    path:     /progressbar
    defaults: { _controller: adminBundle:Admin:progressbar }

nestable:
    path:     /nestable
    defaults: { _controller: adminBundle:Admin:nestable }

rangesl:
    path:     /rangesl
    defaults: { _controller: adminBundle:Admin:rangesl }

timeline:
    path:     /timeline
    defaults: { _controller: adminBundle:Admin:timeline }

typographie2:
    path:     /typographie2
    defaults: { _controller: adminBundle:Admin:typographie2 }

horizental2:
    path:     /horizental2
    defaults: { _controller: adminBundle:Admin:horizental2 }

sessiont:
    path:     /sessiont
    defaults: { _controller: adminBundle:Admin:sessiont }

sessionidle:
    path:     /sessionidle
    defaults: { _controller: adminBundle:Admin:sessionidle }

bootsrap:
    path:     /bootsrap
    defaults: { _controller: adminBundle:Admin:bootsrap }

bradcrump:
    path:     /bradcrump
    defaults: { _controller: adminBundle:Admin:bradcrump }

bootswitch:
    path:     /bootswitch
    defaults: { _controller: adminBundle:Admin:bootswitch }

typographie:
    path:     /typographie
    defaults: { _controller: adminBundle:Admin:typographie }

listmedia:
    path:     /listmedia
    defaults: { _controller: adminBundle:Admin:listmedia }

ribbons:
    path:     /ribbons
    defaults: { _controller: adminBundle:Admin:ribbons }

grid:
    path:     /grid
    defaults: { _controller: adminBundle:Admin:grid }

carousel:
    path:     /carousel
    defaults: { _controller: adminBundle:Admin:carousel }

datep:
    path:     /datep
    defaults: { _controller: adminBundle:Admin:datep }

drag:
    path:     /drag
    defaults: { _controller: adminBundle:Admin:drag }

exemple:
    path:     /exemple
    defaults: { _controller: adminBundle:Admin:exemple }

profil:
    path:     /profil
    defaults: { _controller: adminBundle:Admin:profil }

appcontact:
    path:     /appcontact
    defaults: { _controller: adminBundle:Admin:appcontact }

mapgoogle:
    path:     /mapgoogle
    defaults: { _controller: adminBundle:Admin:mapgoogle }

mapvector:
    path:     /mapvector
    defaults: { _controller: adminBundle:Admin:mapvector }

login2:
    path:     /login2
    defaults: { _controller: adminBundle:Admin:login2 }

register2:
    path:     /register2
    defaults: { _controller: adminBundle:Admin:register2 }

look:
    path:     /look
    defaults: { _controller: adminBundle:Admin:look }

recover:
    path:     /recover
    defaults: { _controller: adminBundle:Admin:recover }


kkk:
    path:     /kkk
    defaults: { _controller: adminBundle:Admin:kkk }








