<?php

namespace ActualiteBundle\Repository;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends \Doctrine\ORM\EntityRepository
{

    function recherche($valeur){
        $query = ActualiteRepository::createQueryBuilder('e')
            ->where('UPPER(e.titre) LIKE UPPER(:valeur)')
            ->orWhere('UPPER(e.contenu) Like UPPER(:valeur)')
            ->setParameter('valeur', '%'.$valeur.'%')
            ->orderBy('e.date', 'DESC')
            ->getQuery();
        return $query->getResult();
    }
}
