<?php

namespace CalendrierMedecinsBundle\Repository;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSerieParametre($s,$t)
    {
        $q = $this->getEntityManager()
            ->createQuery(
                "Select m from CalendrierMedecinsBundle:Patient m 
               where m.nom=:nom and m.prenom=:prenom AND 
               m.date <= CURRENT_DATE() 
               ORDER BY m.date ASC ")
            ->setParameter('nom',$s)
            ->setParameter('prenom',$t);
        return $q->getResult() ;
    }

}
