<?php

namespace GestionBoutiquesBundle\Repository;

/**
 * GerantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GerantRepository extends \Doctrine\ORM\EntityRepository
{
}
